services:
  # Front-end
  client:
    environment:
      - APP_ENV
    container_name: shopping-companion-client
    image: shopping-companion-client
    restart: unless-stopped
    ports:
      - "8080:3000" 
    depends_on:
      - data

  # Microservice pour les données
  data:
    container_name: shopping-companion-data
    image: shopping-companion-data
    environment:
      - APP_ENV
      - DATA_PORT
      - DB_HOST=database
      - DB_USER
      - DB_PASSWORD
      - DB_NAME
      - SECRET_KEY
      - REDIS_HOST=cache
      - REDIS_PORT=6379
    ports:
      - "8082:5000"
    restart: unless-stopped
    depends_on:
      - database
      - redis

  # Microservice d'authentification
  identity:
    environment:
      - APP_ENV
      - PORT
      - DB_HOST=database
      - DB_USER
      - DB_PASSWORD
      - DB_NAME
      - REDIS_HOST=cache
      - REDIS_PORT
      - REDIS_PASSWORD
      - SECRET_KEY
    container_name: shopping-companion-identity
    image: shopping-companion-identity
    ports:
      - "8081:4000"
    restart: unless-stopped
    depends_on:
      - database
      - redis

  redis:
    image: redis:6.0.7
    container_name: redis
    restart: always
    volumes:
      - redis_volume_data:/data
    ports:
      - 6379:6379

  database:
    image: mysql:8.0
    container_name: shopping-companion-db
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=shopping_companion_db
      - TZ=Europe/Paris
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - db_data_production:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  redis_volume_data:
  db_data_production:
