services:
  # Front-end
  client:
    environment:
      - APP_ENV
    container_name: shopping-companion-client
    image: thibaultyvd/shopping-companion-client
    restart: unless-stopped
    ports:
      - "9000:5173" 
    depends_on:
      - data
      - identity

  # Microservice pour les données
  data:
    container_name: shopping-companion-data
    image: thibaultyvd/shopping-companion-data
    environment:
      - APP_ENV
      - DATA_PORT
      - DB_HOST=shopping-companion-db
      - DB_USER
      - DB_PASSWORD
      - DB_NAME
      - SECRET_KEY
    ports:
      - "9001:3000"
    restart: unless-stopped
    depends_on:
      - shopping-companion-db
      - redis

  # Microservice d'authentification
  identity:
    environment:
      - APP_ENV
      - PORT
      - DB_HOST=shopping-companion-db
      - DB_USER
      - DB_PASSWORD
      - DB_NAME
      - SECRET_KEY
    container_name: shopping-companion-identity
    image: thibaultyvd/shopping-companion-identity
    ports:
      - "9002:3000"
    restart: unless-stopped
    depends_on:
      - shopping-companion-db
      - redis

  shopping-companion-db:
    image: mysql:8.0
    container_name: shopping-companion-db
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=shopping_companion_db
      - MYSQL_USER
      - MYSQL_PASSWORD
      - TZ=Europe/Paris
    restart: always
    ports:
      - '9003:3306'
    volumes:
      - db_data_production:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7
    container_name: shopping-companion-redis
    restart: unless-stopped
    ports:
      - "9004:6379"

volumes:
  db_data_production: