version: '3'
services:
  client:
    ports:
      - 8080:3000
    volumes:
      - './shopping-companion:/home/shopping-companion-volume'
    image: shopping-companion:latest
    restart: unless-stopped

volumes:
  shoppingcompanion: